package multiplayer;

public enum MessageType {
	SIDE_ASSIGNMENT, PLAYER_CONTROL, NEW_GAME_STARTING, GAME_OVER,
	ENTITY_REMOVED, ENTITY_UPDATED, ENTITY_ADDED, LOCATION_UPDATE,
	VIEW_WORMHOLE_AFFECT, VIEW_DISINTEGRATE_ASTEROID, VIEW_PLAYER_HIT, VIEW_MIRROR_BOUNCE, VIEW_BULLET_ASTEROID_HIT,
	}
